name: Ligti
favicon: null
layout_spectrum: 0.54106
typography_spectrum: 0.69773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58585a'
    - '#8cc63f'
    - '#e7e8e9'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.875
  lightness: 0.3045596268493682
  saturation: 0.27215599501505494
  rhythmicContrast: 0.1871578972786665
purpose: []
